@startuml

title Вариант использования- Проверить Поставщика

actor        "Менеджер"
participant  "Сервис заявок"
participant  "Брокер сообщений"
participant  "Сервис взаимодействия с внешней ИС"
participant  "База данных Поставщиков"
participant  "Сервис скоринга"

autonumber
activate "Сервис заявок"
Менеджер -> "Сервис заявок": Вызов операции "Проверить поставщика"
"Сервис заявок" -> "Сервис заявок": Проверить состояние заявки Поставщика


alt Состояние заявки = "Ожидает согласования"
    "Сервис заявок" -> "Брокер сообщений" : Опубликовать запрос на проверку Поставщика
    activate "Брокер сообщений"
    "Сервис заявок" -> "Сервис заявок": Меняет состояние заявки Поставщика="отправлена на проверку"
    "Брокер сообщений" -> "Сервис взаимодействия с внешней ИС" : опубликовать запрос на проверку Поставщика
    activate "Сервис взаимодействия с внешней ИС"
    "Сервис взаимодействия с внешней ИС" -> "База данных Поставщиков" : Отправить запрос на проверку Поставщика
     activate "База данных Поставщиков"
    "База данных Поставщиков" -> "Сервис взаимодействия с внешней ИС": получить ответ на запрос проверки Поставщика в "БД Поставщиков"
     "Сервис взаимодействия с внешней ИС" -> "Брокер сообщений" : Отправить ответ о проверке Поставщика
     deactivate "База данных Поставщиков"
     deactivate "Сервис взаимодействия с внешней ИС"
    "Брокер сообщений" -> "Сервис скоринга" : отправляет сообщение о запуске процедуры скоринга
    activate "Сервис скоринга"
    "Сервис скоринга" -> "Брокер сообщений" : отправляет результат скоринга
    "Сервис скоринга" -> "Брокер сообщений" : оповещение о завершении процедуры скоринга (для Орекстратора)

    deactivate "Сервис скоринга"
    "Брокер сообщений" ->  "Сервис заявок" :  Опубликовать результат проверки Поставщика
    deactivate "Брокер сообщений"

    alt Ответ получен
        alt Поставщик найден
            alt Проверка Поставщика пройдена успешна
                "Сервис заявок" -> "Сервис заявок" : изменить статус заявки на "Принята"
            else Проверка Поставщика не пройдена
                "Сервис заявок" -> "Сервис заявок" : изменить статус заявки на "Отказано"
            end alt
        else Поставщик не найден
            "Сервис заявок" -> "Сервис заявок" : изменить статус заявки на "Ручное согласование"
        end alt
        "Сервис заявок" -> "Менеджер" : сообщение результатах проверки Поставщика
    else Ответ не получен
        "Сервис заявок" -> "Менеджер" : сообщение об ошибке и предложение повторить обработку позже
    end alt


else Состояние заявки <> "Ожидает согласования"
    "Сервис заявок" -> "Менеджер" : сообщение о неверном состоянии заявки Поставщика
end alt


@enduml