@startuml
'https://plantuml.com/activity-diagram-beta

start
:Авторизация/регистрация Клиента на сайте;
if (Авторизация успешна?) then (Да)
  :Оформление заказа;
  :Проверка наличия товара на складе;
  if (Товар есть в наличии?) then (Да)
 else (нет)
 :Уведомить клиента;
 fork
 :Выбрать альтернативный товар;
 fork again
 :Оставить в ожидании поступления;
 fork again
 :Автоматическое уведомление клиента о поступлении товара;
 end fork;
endif

if (В заказе имеются товары для оплаты?) then (ДА)
  fork
    :Применить промокод;
    if (Промокод ввели верно?
        Не превысили лимит?
        Действует на товары?) then (Да)
        :Обновить сумму заказа c учетом скидки;
    else (Нет)
    end if
   :Выбрать способ оплаты;
   fork again
   :Подготовка товара к отправке;
  end fork;

    if (Оплата прошла успешно и товар готов к отправке?) then (Да)
      fork
      :Генерации счета фактуры;
      fork again
      :Отправка уведомления Клиенту;
      fork again
       :Меняется статус заказа на "Отправлен"";
      end fork;
    else (нет)
       :Уведомить Клиента о проблеме с платежом;
        if (Повторить оплату/изменить способ оплаты ?) then (Да)
           :Оплата заказа;
        else (нет)
        fork
         :Отменить заказ;
        fork again
         :Вернуть деньги Клиенту;
        end fork
        endif
    endif
:Обновление статуса заказа;
:Отправка уведомления клиенту;
endif
endif
stop

@enduml
